// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ApiSalvarVidas.Models;

namespace ApiSalvarVidas.Models;

public partial class Animale
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(50)]
    public string Tipo { get; set; }

    [StringLength(100)]
    public string Raza { get; set; }

    public int Edad { get; set; }

    public string Foto { get; set; }

    public int Estado { get; set; }

    [InverseProperty("Animal")]
    public virtual AnimalesComunitario AnimalesComunitario { get; set; }

    [InverseProperty("Animal")]
    public virtual AnimalesEnAdopcion AnimalesEnAdopcion { get; set; }

    [InverseProperty("Animal")]
    public virtual AnimalesEnTransito AnimalesEnTransito { get; set; }

    [InverseProperty("Animal")]
    public virtual ICollection<AnimalesPerdidosEncontrado> AnimalesPerdidosEncontrados { get; set; } = new List<AnimalesPerdidosEncontrado>();
}