// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ApiSalvarVidas.Models;

namespace ApiSalvarVidas.Models;

[Index("AnimalId", Name = "IX_AnimalesPerdidosEncontrados_AnimalId")]
public partial class AnimalesPerdidosEncontrado
{
    [Key]
    public int Id { get; set; }

    public int? AnimalId { get; set; }

    [Required]
    [StringLength(300)]
    public string Descripcion { get; set; }

    [Required]
    [StringLength(150)]
    public string Direccion { get; set; }

    [Required]
    public string TelefonoContacto { get; set; }

    public DateTime Fecha { get; set; }

    [ForeignKey("AnimalId")]
    [InverseProperty("AnimalesPerdidosEncontrados")]
    public virtual Animale Animal { get; set; }
}