// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiSalvarVidas.Models;

[Index("AnimalId", Name = "IX_AnimalesComunitarios_AnimalId", IsUnique = true)]
public partial class AnimalesComunitario
{
    [Key]
    public int Id { get; set; }

    public int AnimalId { get; set; }

    [Required]
    [StringLength(150)]
    public string LugarHabitual { get; set; }

    public bool AptoParaAdopcion { get; set; }

    [ForeignKey("AnimalId")]
    [InverseProperty("AnimalesComunitario")]
    public virtual Animale Animal { get; set; }
}