// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiSalvarVidas.Models;

[Table("AnimalesEnTransito")]
[Index("AnimalId", Name = "IX_AnimalesEnTransito_AnimalId", IsUnique = true)]
[Index("FamiliaId", Name = "IX_AnimalesEnTransito_FamiliaId")]
public partial class AnimalesEnTransito
{
    [Key]
    public int Id { get; set; }

    public int AnimalId { get; set; }

    public int? FamiliaId { get; set; }

    public DateTime FechaIngreso { get; set; }

    public DateTime? FechaSalida { get; set; }

    [ForeignKey("AnimalId")]
    [InverseProperty("AnimalesEnTransito")]
    public virtual Animale Animal { get; set; }

    [ForeignKey("FamiliaId")]
    [InverseProperty("AnimalesEnTransitos")]
    public virtual Familia Familia { get; set; }
}