// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiSalvarVidas.Models;

[Table("AnimalesEnAdopcion")]
[Index("AnimalId", Name = "IX_AnimalesEnAdopcion_AnimalId", IsUnique = true)]
[Index("FamiliaId", Name = "IX_AnimalesEnAdopcion_FamiliaId")]
public partial class AnimalesEnAdopcion
{
    [Key]
    public int Id { get; set; }

    public int AnimalId { get; set; }

    public int FamiliaId { get; set; }

    public DateTime FechaAdopcion { get; set; }

    [ForeignKey("AnimalId")]
    [InverseProperty("AnimalesEnAdopcion")]
    public virtual Animale Animal { get; set; }

    [ForeignKey("FamiliaId")]
    [InverseProperty("AnimalesEnAdopcions")]
    public virtual Familia Familia { get; set; }
}