// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiSalvarVidas.Models;

public partial class Familia
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(150)]
    public string Direccion { get; set; }

    [Required]
    public string Telefono { get; set; }

    [InverseProperty("Familia")]
    public virtual ICollection<AnimalesEnAdopcion> AnimalesEnAdopcions { get; set; } = new List<AnimalesEnAdopcion>();

    [InverseProperty("Familia")]
    public virtual ICollection<AnimalesEnTransito> AnimalesEnTransitos { get; set; } = new List<AnimalesEnTransito>();
}