// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiSalvarVidas.Models;

[Keyless]
public partial class FiltrarAnimale
{
    public int Id { get; set; }

    [Required]
    public string Nombre { get; set; }

    [Required]
    public string Tipo { get; set; }

    public string Raza { get; set; }

    public int Edad { get; set; }

    public string Foto { get; set; }

    public int Estado { get; set; }
}